import { WebDesignConfig, Block, Page } from '../types';

// Map icon names to Bootstrap Icons or Lucide CSS classes for accurate Laravel blade styling
export function getBootstrapIconClass(icon: string): string {
  const iconMap: Record<string, string> = {
    Sparkles: 'bi-stars',
    Database: 'bi-database',
    Cpu: 'bi-cpu',
    Shield: 'bi-shield-check',
    Zap: 'bi-lightning-charge-fill',
    Box: 'bi-box-seam',
    ShoppingCart: 'bi-cart4',
    Users: 'bi-people-fill',
    Heart: 'bi-heart-fill',
    Star: 'bi-star-fill',
    Globe: 'bi-globe',
    TrendingUp: 'bi-graph-up-arrow'
  };
  return iconMap[icon] || 'bi-bookmark-star-fill';
}

export function generateLaravelFiles(config: WebDesignConfig): Record<string, string> {
  const files: Record<string, string> = {};
  const activePage = config.pages.find(p => p.id === config.activePageId) || config.pages[0];
  const primaryColor = config.colorPalette.primary;
  const secondaryColor = config.colorPalette.secondary;
  const darkColor = config.colorPalette.dark;
  const lightColor = config.colorPalette.light;
  
  // 1. web.php Routing
  files['routes/web.php'] = `<?php

use App\\Http\\Controllers\\HomeController;
use Illuminate\\Support\\Facades\\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your CMS website application.
| Generated by LaraBoot Visual Builder CMS.
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
${config.pages.filter(p => p.id !== 'home').map(p => {
  return `Route::get('/${p.slug}', [HomeController::class, '${p.slug}'])->name('${p.id}');`;
}).join('\n')}
`;

  // 2. HomeController.php
  files['app/Http/Controllers/HomeController.php'] = `<?php

namespace App\\Http\\Controllers;

use Illuminate\\Http\\Request;
use App\\Models\\BlogPost;
use App\\Models\\Product;

class HomeController extends Controller
{
    /**
     * Display the CMS dynamically computed landing page.
     */
    public function index()
    {
        // Load CMS blogs and products databases seamlessly
        $blogs = BlogPost::orderBy('created_at', 'desc')->get();
        $products = Product::where('in_stock', true)->get();

        return view('welcome', [
            'projectName' => '${config.projectName}',
            'blogs' => $blogs,
            'products' => $products,
            'colorScheme' => [
                'primary' => '${primaryColor}',
                'secondary' => '${secondaryColor}'
            ]
        ]);
    }
${config.pages.filter(p => p.id !== 'home').map(p => `
    /**
     * Display the ${p.title} page.
     */
    public function ${p.slug}()
    {
        return view('pages.${p.slug}', [
            'projectName' => '${config.projectName}',
            'colorScheme' => [
                'primary' => '${primaryColor}',
                'secondary' => '${secondaryColor}'
            ]
        ]);
    }
`).join('\n')}
}
`;

  // 3. Blog & Product Models
  files['app/Models/BlogPost.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class BlogPost extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'category',
        'author',
        'image_url'
    ];
}
`;

  files['app/Models/Product.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class Product extends Model
{
    use HasFactory;

    protected $casts = [
        'in_stock' => 'boolean',
        'price' => 'decimal:2'
    ];
}
`;

  // 4. database/migrations/xxx_create_cms_tables.php
  files['database/migrations/2026_06_16_000000_create_cms_tables.php'] = `<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    /**
     * Run the migrations for static and dynamic cms bindings.
     */
    public function up(): void
    {
        Schema::create('blog_posts', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->text('excerpt');
            $table->text('body');
            $table->string('category')->nullable();
            $table->string('author')->nullable();
            $table->string('image_url')->nullable();
            $table->timestamps();
        });

        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->unique();
            $table->decimal('price', 10, 2);
            $table->text('description');
            $table->string('image_url')->nullable();
            $table->boolean('in_stock')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('blog_posts');
        Schema::dropIfExists('products');
    }
};
`;

  // 5. database/seeders/DatabaseSeeder.php
  files['database/seeders/DatabaseSeeder.php'] = `<?php

namespace Database\\Seeders;

use Illuminate\\Database\\Seeder;
use App\\Models\\BlogPost;
use App\\Models\\Product;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database with LaraBoot CMS mock records.
     */
    public function run(): void
    {
        // Seeding interactive blog posts
        ${(config.blogModels || []).map(b => `
        BlogPost::create([
            'title' => '${(b.title || '').replace(/'/g, "\\'")}',
            'slug' => '${b.slug || ''}',
            'excerpt' => '${(b.excerpt || '').replace(/'/g, "\\'")}',
            'body' => '${(b.body || '').replace(/'/g, "\\'")}',
            'category' => '${(b.category || '').replace(/'/g, "\\'")}',
            'author' => '${(b.author || '').replace(/'/g, "\\'")}',
            'image_url' => '${(b.imageUrl || '').replace(/'/g, "\\'")}'
        ]);`).join('\n')}

        // Seeding products
        ${(config.productModels || []).map(p => {
          const rawPrice = p.price != null ? String(p.price) : '0';
          const cleanPrice = parseFloat(rawPrice.replace(/[^0-9.]/g, '')) || 0.00;
          return `
        Product::create([
            'name' => '${(p.name || '').replace(/'/g, "\\'")}',
            'slug' => '${p.slug || ''}',
            'price' => ${cleanPrice.toFixed(2)},
            'description' => '${(p.description || '').replace(/'/g, "\\'")}',
            'image_url' => '${(p.imageUrl || '').replace(/'/g, "\\'")}',
            'in_stock' => ${p.inStock ? 'true' : 'false'}
        ]);`;
        }).join('\n')}
    }
}
`;

  // 6. resources/views/layouts/app.blade.php (Main Master Page)
  files['resources/views/layouts/app.blade.php'] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', '${activePage.title}') - {{ $projectName ?? '${config.projectName}' }}</title>
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet font-display: swap">
    
    <!-- Custom Style variables based on CMS Color Palette -->
    <style>
        :root {
            --bs-primary: ${primaryColor};
            --bs-secondary: ${secondaryColor};
            --bs-primary-rgb: ${hexToRgb(primaryColor)};
            --bs-secondary-rgb: ${hexToRgb(secondaryColor)};
            --cms-dark: ${darkColor};
            --cms-light: ${lightColor};
        }
        body {
            font-family: '${config.colorPalette.fontFamily}', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background-color: var(--cms-light);
            color: var(--cms-dark);
        }
        .btn-primary {
            background-color: var(--bs-primary);
            border-color: var(--bs-primary);
        }
        .btn-primary:hover, .btn-primary:focus {
            background-color: darkslategray; /* slightly darker primary override */
            filter: brightness(0.9);
        }
        .text-primary {
            color: var(--bs-primary) !important;
        }
        .gradient-banner {
            background: linear-gradient(135deg, var(--bs-primary) 0%, var(--bs-secondary) 100%);
            color: white;
        }
        .glass-card {
            background: rgba(255, 255, 255, 0.7);
            backdrop-filter: blur(8px);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
    </style>
</head>
<body>

    @yield('content')

    <!-- Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
`;

  // 7. resources/views/welcome.blade.php (Home View)
  files['resources/views/welcome.blade.php'] = generateBladeViewString(activePage.blocks, true, config.projectName);

  // 8. Other sub-pages inside resources/views/pages/
  config.pages.filter(p => p.id !== 'home').forEach(p => {
    files[`resources/views/pages/${p.slug}.blade.php`] = generateBladeViewString(p.blocks, false, config.projectName);
  });

  // 9. Laravel Config and Standard Boilerplate files
  files['composer.json'] = `{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework website custom generated by LaraBoot CMS.",
    "keywords": ["framework", "laravel", "bootstrap"],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "laravel/framework": "^11.0",
        "laravel/tinker": "^2.9"
    },
    "autoload": {
        "psr-4": {
            "App\\\\": "app/",
            "Database\\\\Factories\\\\": "database/factories/",
            "Database\\\\Seeders\\\\": "database/seeders/"
        }
    }
}`;

  files['package.json'] = `{
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "devDependencies": {
    "bootstrap": "^5.3.3",
    "laravel-vite-plugin": "^1.0",
    "vite": "^5.0"
  }
}`;

  files['vite.config.js'] = `import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});`;

  const hostVal = config.dbHost || '127.0.0.1';
  let defaultPort = '3306';
  if (config.dbDriver === 'pgsql') {
    defaultPort = '5432';
  } else if (config.dbDriver === 'sqlite') {
    defaultPort = '';
  }
  const portVal = config.dbPort !== undefined ? config.dbPort : defaultPort;
  const dbNameVal = config.dbDatabase || config.projectName || 'laravel';
  const usernameVal = config.dbUsername !== undefined ? config.dbUsername : 'root';
  const passwordVal = config.dbPassword !== undefined ? config.dbPassword : '';

  files['.env.example'] = `APP_NAME="${config.projectName || 'LaraBoot'}"
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost:8000

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=${config.dbDriver || 'sqlite'}
DB_HOST=${hostVal}
DB_PORT=${portVal}
DB_DATABASE=${dbNameVal}
DB_USERNAME=${usernameVal}
DB_PASSWORD=${passwordVal}

SESSION_DRIVER=cookie
SESSION_LIFETIME=120
`;

  files['database/database.sqlite'] = '';

  files['artisan'] = `#!/usr/bin/env php
<?php

// Laravel Command Line Tool
// Generated automatically by LaraBoot CMS Visual Compiler.

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Boot Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\\Contracts\\Console\\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\\Component\\Console\\Input\\ArgvInput,
    new Symfony\\Component\\Console\\Output\\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
`;

  files['bootstrap/app.php'] = `<?php

use Illuminate\\Foundation\\Application;
use Illuminate\\Foundation\\Configuration\\Exceptions;
use Illuminate\\Foundation\\Configuration\\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        // Middleware customized by LaraBoot Studio
    })
    ->withExceptions(function (Exceptions $exceptions) {
        // Exception management
    })->create();
`;

  files['bootstrap/providers.php'] = `<?php

return [
    App\\Providers\\AppServiceProvider::class,
];
`;

  files['app/Providers/AppServiceProvider.php'] = `<?php

namespace App\\Providers;

use Illuminate\\Support\\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        //
    }
}
`;

  files['routes/console.php'] = `<?php

use Illuminate\\Support\\Facades\\Artisan;

Artisan::command('inspire', function () {
    $this->comment(Illuminate\\Foundation\\Inspiring::quote());
})->purpose('Display an inspiring quote');
`;

  files['public/index.php'] = `<?php

use Illuminate\\Http\\Request;

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/../storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer autoloader...
require __DIR__.'/../vendor/autoload.php';

// Bootstrap Laravel and handle the request...
(require_once __DIR__.'/../bootstrap/app.php')
    ->handleRequest(Request::capture());
`;

  files['config/database.php'] = `<?php

return [

    'default' => env('DB_CONNECTION', '${config.dbDriver || 'sqlite'}'),

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DB_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8'),
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],

    ],

    'migrations' => 'migrations',

];
`;

  files['resources/css/app.css'] = `/* Custom Styles compiled by LaraBoot CMS Studio */
@import "bootstrap/dist/css/bootstrap.min.css";
`;

  files['resources/js/app.js'] = `// Main JS compiled by LaraBoot CMS Studio
import 'bootstrap';
`;

  files['README.md'] = `# ${config.projectName} - Laravel CMS Website
Generated with **LaraBoot Visual Builder CMS** on ${new Date().toLocaleDateString()}.

This is a complete, fully engineered Laravel MVC codebase featuring pristine **Bootstrap 5** visual scaffolding, database models, seeders, and routes fully configured.

## Getting Started

1. Extract the contents to your local server directory.
2. Run Composer dependency installs:
   \`\`\`bash
   composer install
   \`\`\`
3. Setup your environment config:
   \`\`\`bash
   cp .env.example .env
   php artisan key:generate
   \`\`\`
4. Run Database Migrations and Seed mock blog entries & products:
   \`\`\`bash
   php artisan migrate --seed
   \`\`\`
5. Compile assets and launch development servers:
   \`\`\`bash
   npm install
   npm run dev
   # In another terminal window:
   php artisan serve
   \`\`\`

Open your browser at \`http://localhost:8000\` to experience your Bootstrap design running on Laravel!
`;

  return files;
}

// Convert Hex string color to RGB coordinates for CSS translucent overlays
function hexToRgb(hex: string): string {
  let c = hex.substring(1);
  if (c.length === 3) {
    c = c[0] + c[0] + c[1] + c[1] + c[2] + c[2];
  }
  const num = parseInt(c, 16);
  return `${(num >> 16) & 255}, ${(num >> 8) & 255}, ${num & 255}`;
}

// Subroutine: convert block list directly to highly optimized Laravel Blade code
function generateBladeViewString(blocks: Block[], isHome: boolean, projectName: string = 'Laraboot'): string {
  let content = `@extends('layouts.app')

@section('title', '${isHome ? 'Welcome Portal' : 'Custom Section'}')

@section('content')
`;

  blocks.forEach(block => {
    if (!block.visible) return;

    switch (block.type) {
      case 'navbar': {
        const bgClass = block.themeStyle === 'dark' ? 'bg-dark navbar-dark' : block.themeStyle === 'primary' ? 'bg-primary navbar-dark' : 'bg-light navbar-light';
        content += `
    <!-- Navbar Section: ${block.brand} -->
    <nav class="navbar navbar-expand-lg ${bgClass} ${block.sticky ? 'sticky-top shadow' : ''} py-3">
        <div class="container">
            <a class="navbar-brand fw-bold fs-3" href="#">
                <i class="bi bi-cpu text-primary me-2"></i>{{ $projectName ?? '${block.brand}' }}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navCollapse-${block.id}">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navCollapse-${block.id}">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    ${block.links.map(link => `
                    <li class="nav-item">
                        <a class="nav-link px-3" href="${link.url}">${link.label}</a>
                    </li>`).join('')}
                </ul>
                <a href="${block.ctaLink}" class="btn btn-primary px-4 rounded-pill fw-semibold shadow-sm">${block.ctaText}</a>
            </div>
        </div>
    </nav>
`;
        break;
      }
      case 'hero': {
        let alignClass = 'text-center py-5';
        let rowContent = '';
        const bgClass = block.bgPattern === 'gradient' ? 'gradient-banner' : block.bgPattern === 'glass' ? 'bg-body-tertiary border-bottom py-5 glass-card' : 'bg-body py-5';

        if (block.layout === 'center') {
          rowContent = `
                <div class="col-lg-8 mx-auto">
                    <h1 class="display-4 fw-bold mb-3 tracking-tight">${block.title}</h1>
                    <p class="lead mb-4 opacity-90">${block.subtitle}</p>
                    <div class="d-flex justify-content-center gap-3">
                        <a href="${block.ctaLink}" class="btn btn-primary btn-lg px-4 rounded-pill shadow">${block.ctaText}</a>
                        <a href="${block.secondaryCtaLink}" class="btn btn-outline-dark btn-lg px-4 rounded-pill">${block.secondaryCtaText}</a>
                    </div>
                </div>`;
        } else if (block.layout === 'left-split') {
          rowContent = `
                <div class="col-lg-6 my-auto text-start">
                    <span class="badge bg-primary-subtle text-primary border border-primary-subtle px-3 py-2 rounded-pill mb-3 uppercase tracking-wider">Laravel + Bootstrap</span>
                    <h1 class="display-5 fw-bold mb-3">${block.title}</h1>
                    <p class="lead mb-4 opacity-90">${block.subtitle}</p>
                    <div class="d-flex gap-3">
                        <a href="${block.ctaLink}" class="btn btn-primary btn-lg px-4 rounded-pill shadow-sm">${block.ctaText}</a>
                        <a href="${block.secondaryCtaLink}" class="btn btn-outline-secondary btn-lg px-4 rounded-pill">${block.secondaryCtaText}</a>
                    </div>
                </div>
                <div class="col-lg-6 mt-4 mt-lg-0">
                    <img src="${block.imageUrl}" class="img-fluid rounded-4 shadow-lg border" alt="Hero Mockup" referrerPolicy="no-referrer">
                </div>`;
        } else {
          rowContent = `
                <div class="col-lg-6 mb-4 my-auto">
                    <img src="${block.imageUrl}" class="img-fluid rounded-4 shadow-lg border" alt="Hero Mockup" referrerPolicy="no-referrer">
                </div>
                <div class="col-lg-6 my-auto text-start ps-lg-5">
                    <h1 class="display-5 fw-bold mb-3">${block.title}</h1>
                    <p class="lead mb-4 opacity-90">${block.subtitle}</p>
                    <div class="d-flex gap-3">
                        <a href="${block.ctaLink}" class="btn btn-primary btn-lg px-4 rounded-pill shadow-sm">${block.ctaText}</a>
                        <a href="${block.secondaryCtaLink}" class="btn btn-outline-secondary btn-lg px-4 rounded-pill">${block.secondaryCtaText}</a>
                    </div>
                </div>`;
        }

        content += `
    <!-- Hero Block -->
    <header class="${bgClass} py-5 border-bottom">
        <div class="container py-4">
            <div class="row align-items-center">
                ${rowContent}
            </div>
        </div>
    </header>
`;
        break;
      }
      case 'features': {
        const colClass = block.columns === 4 ? 'col-lg-3' : block.columns === 2 ? 'col-lg-6' : 'col-lg-4';
        content += `
    <!-- Features Block: ${block.title} -->
    <section id="features" class="py-5 bg-body-secondary">
        <div class="container py-4 text-center">
            <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
            <p class="text-secondary col-md-8 mx-auto mb-5 lead">${block.subtitle}</p>
            <div class="row g-4 text-start">
                ${block.items.map(item => `
                <div class="${colClass} col-md-6">
                    <div class="card h-100 p-4 border shadow-sm rounded-4 bg-body">
                        <div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 text-primary fs-3 rounded-3 p-3 mb-3" style="width: 56px; height: 56px;">
                            <i class="bi ${getBootstrapIconClass(item.icon)}"></i>
                        </div>
                        <h4 class="fw-bold mb-2 text-dark">${item.title}</h4>
                        <p class="text-secondary small mb-0">${item.description}</p>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'stats': {
        content += `
    <!-- Stats Banner: ${block.title} -->
    <section class="py-5 gradient-banner text-center text-white">
        <div class="container py-3">
            <h3 class="fw-bold mb-3">${block.title}</h3>
            <p class="lead opacity-90 col-md-8 mx-auto mb-5">${block.subtitle}</p>
            <div class="row g-4 justify-content-center">
                ${block.items.map(item => `
                <div class="col-6 col-md-3">
                    <h2 class="display-4 fw-extrabold mb-1">${item.number}</h2>
                    <p class="text-uppercase tracking-wider small opacity-75 mb-0">${item.label}</p>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'blog': {
        content += `
    <!-- Blog Section -->
    <section id="blog" class="py-5 bg-body">
        <div class="container py-4">
            <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-5">
                <div>
                    <h2 class="fw-bold text-dark display-6 mb-1">${block.title}</h2>
                    <p class="text-secondary lead mb-0">${block.subtitle}</p>
                </div>
                <a href="#" class="btn btn-outline-primary rounded-pill mt-3 mt-md-0 px-4">View All Publications</a>
            </div>

            @if(isset($blogs) && count($blogs) > 0)
                <div class="row g-4">
                    @foreach($blogs as $post)
                        <div class="col-lg-6">
                            <div class="card h-100 border rounded-4 overflow-hidden shadow-sm bg-body">
                                <div class="row g-0 h-100">
                                    <div class="col-md-5">
                                        <img src="{{ $post->image_url ?? 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=400&q=80' }}" class="img-fluid h-100 object-fit-cover w-full" style="min-height: 200px;" alt="{{ $post->title }}">
                                    </div>
                                    <div class="col-md-7 d-flex flex-column p-4">
                                        <span class="badge bg-secondary-subtle text-secondary align-self-start mb-2">{{ $post->category ?? 'News' }}</span>
                                        <h5 class="fw-bold text-dark"><a href="#" class="text-decoration-none text-dark">{{ $post->title }}</a></h5>
                                        <p class="text-secondary small flex-grow-1">{{ Str::limit($post->excerpt, 100) }}</p>
                                        <div class="d-flex align-items-center mt-3 pt-3 border-top justify-content-between">
                                            <span class="text-secondary small fw-semibold">{{ $post->author ?? 'Editorial Staff' }}</span>
                                            <span class="text-muted small">{{ $post->created_at ? $post->created_at->format('M d, Y') : 'June 2026' }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            @else
                <!-- Static Fallback Content when not run in production server -->
                <div class="row g-4">
                    <div class="col-lg-6">
                        <div class="card h-100 border rounded-4 overflow-hidden shadow-sm bg-body">
                            <div class="row g-0">
                                <div class="col-md-5">
                                    <img src="https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=400&q=80" class="img-fluid h-100 object-fit-cover" alt="CMS Dev">
                                </div>
                                <div class="col-md-7 p-4 d-flex flex-column justify-content-between">
                                    <div>
                                        <span class="badge bg-secondary-subtle text-secondary mb-2">DevOps</span>
                                        <h5 class="fw-bold text-dark">Deploying Laravel 11 on Modern VPS Hosting</h5>
                                        <p class="text-secondary small">Learn the step-by-step procedure to config PHP 8.3, Nginx, and systemd with custom seeders.</p>
                                    </div>
                                    <div class="text-muted small">Sarah Taylor | June 2026</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </section>
`;
        break;
      }
      case 'pricing': {
        content += `
    <!-- Pricing Section: ${block.title} -->
    <section id="pricing" class="py-5 bg-body-secondary">
        <div class="container py-4 text-center">
            <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
            <p class="text-secondary lead col-md-8 mx-auto mb-5">${block.subtitle}</p>
            <div class="row g-4 justify-content-center text-start">
                ${block.tiers.map(tier => `
                <div class="col-lg-4 col-md-6">
                    <div class="card h-100 p-4 border ${tier.featured ? 'border-primary border-3 shadow-lg scale-up' : 'shadow-sm'} rounded-4 bg-body d-flex flex-column">
                        ${tier.featured ? '<span class="badge bg-primary text-white rounded-pill px-3 py-2 align-self-start mb-3 uppercase tracking-wider">Most Popular</span>' : ''}
                        <h4 class="fw-bold text-dark mb-1">${tier.name}</h4>
                        <div class="d-flex align-items-baseline mb-3">
                            <span class="display-5 fw-bold text-dark">${tier.price}</span>
                            <span class="text-secondary ms-2">${tier.billing}</span>
                        </div>
                        <ul class="list-unstyled flex-grow-1 border-top pt-3 mb-4">
                            ${tier.features.map(f => `
                            <li class="mb-2 d-flex align-items-center">
                                <i class="bi bi-patch-check-fill text-success me-2"></i>
                                <span class="text-secondary">${f}</span>
                            </li>`).join('')}
                        </ul>
                        <a href="#" class="btn ${tier.featured ? 'btn-primary' : 'btn-outline-dark'} btn-lg w-full rounded-pill shadow-sm py-2 fw-semibold">${tier.ctaText}</a>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'testimonials': {
        content += `
    <!-- Testimonials Section -->
    <section class="py-5 bg-body">
        <div class="container py-4 text-center">
            <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
            <p class="text-secondary col-md-8 mx-auto mb-5 lead">${block.subtitle}</p>
            <div class="row g-4 text-start">
                ${block.items.map(item => `
                <div class="col-md-6 col-lg-4">
                    <div class="card h-100 p-4 border rounded-4 shadow-sm bg-body d-flex flex-column justify-content-between">
                        <div>
                            <div class="text-warning mb-3">
                                ${Array.from({ length: item.stars }).map(() => '<i class="bi bi-star-fill me-1"></i>').join('')}
                            </div>
                            <p class="text-secondary italic mb-4">"${item.text}"</p>
                        </div>
                        <div class="d-flex align-items-center border-top pt-3">
                            <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-flex align-items-center justify-content-center fw-bold me-3" style="width: 44px; height: 44px;">
                                ${item.author[0]}
                            </div>
                            <div>
                                <h6 class="fw-bold text-dark mb-0">${item.author}</h6>
                                <small class="text-muted">${item.role}</small>
                            </div>
                        </div>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'gallery': {
        const colClass = block.columns === 4 ? 'col-lg-3' : 'col-lg-4';
        content += `
    <!-- Gallery Block: ${block.title} -->
    <section class="py-5 bg-body-secondary">
        <div class="container py-4">
            <div class="text-center mb-5">
                <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
                <p class="text-secondary lead col-md-8 mx-auto">${block.subtitle}</p>
            </div>
            <div class="row g-4">
                ${block.items.map(img => `
                <div class="${colClass} col-md-6">
                    <div class="card h-100 overflow-hidden border shadow-sm rounded-4 bg-body">
                        <img src="${img.imageUrl}" class="img-fluid" style="height: 220px; object-fit: cover;" alt="${img.title}" referrerPolicy="no-referrer">
                        <div class="p-3">
                            <h5 class="fw-bold text-dark mb-1">${img.title}</h5>
                            <p class="text-secondary small mb-0">${img.description}</p>
                        </div>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'contact': {
        content += `
    <!-- Contact/Form Block -->
    <section id="contact" class="py-5 bg-body">
        <div class="container py-4">
            <div class="row g-5 align-items-stretch">
                <div class="col-lg-5 d-flex flex-column justify-content-between">
                    <div>
                        <span class="badge bg-primary-subtle text-primary border border-primary-subtle px-3 py-2 rounded-pill mb-3">Support & Launch</span>
                        <h2 class="fw-bold text-dark display-6 mb-3">${block.title}</h2>
                        <p class="text-secondary mb-4 lead">${block.subtitle}</p>
                    </div>
                    <div class="mb-4">
                        <div class="d-flex align-items-center mb-3">
                            <span class="bg-primary bg-opacity-10 text-primary p-2 rounded-3 me-3 fs-3"><i class="bi bi-envelope"></i></span>
                            <div>
                                <h6 class="fw-bold mb-0">Email Address</h6>
                                <span class="text-secondary small">${block.email}</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center mb-3">
                            <span class="bg-primary bg-opacity-10 text-primary p-2 rounded-3 me-3 fs-3"><i class="bi bi-telephone"></i></span>
                            <div>
                                <h6 class="fw-bold mb-0">Telephone Support</h6>
                                <span class="text-secondary small">${block.phone}</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="bg-primary bg-opacity-10 text-primary p-2 rounded-3 me-3 fs-3"><i class="bi bi-geo-alt"></i></span>
                            <div>
                                <h6 class="fw-bold mb-0">Silicon HQ Location</h6>
                                <span class="text-secondary small">${block.address}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7">
                    <form class="card p-4 p-md-5 border shadow-sm rounded-4 bg-body" onsubmit="event.preventDefault(); alert('Standard Laravel Form Action simulation success! Thank you.');">
                        <div class="row g-3">
                            <div class="col-md-6">
                                <label class="form-label text-secondary small fw-semibold">Your Full Name</label>
                                <input type="text" class="form-control rounded-pill py-2 px-3" required placeholder="Alex Mercer">
                            </div>
                            <div class="col-md-6">
                                <label class="form-label text-secondary small fw-semibold">Email Account</label>
                                <input type="email" class="form-control rounded-pill py-2 px-3" required placeholder="alex@mercer.com">
                            </div>
                            <div class="col-12">
                                <label class="form-label text-secondary small fw-semibold">Inquiry Subject</label>
                                <input type="text" class="form-control rounded-pill py-2 px-3" required placeholder="Laravel Deployment Assistance">
                            </div>
                            <div class="col-12">
                                <label class="form-label text-secondary small fw-semibold">Message Body</label>
                                <textarea class="form-control rounded-3" rows="4" required placeholder="Please describe your operational needs here..."></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary rounded-pill w-100 py-3 fw-semibold shadow-sm mt-3">${block.buttonText}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'footer': {
        content += `
    <!-- Footer section -->
    <footer class="py-5 bg-dark text-white border-top">
        <div class="container py-3">
            <div class="row g-4 align-items-center justify-content-between">
                <div class="col-md-5">
                    <h5 class="fw-bold text-white mb-3"><i class="bi bi-cpu text-primary me-2"></i>{{ $projectName ?? '${projectName}' }}</h5>
                    <p class="text-secondary small mb-0">${block.text}</p>
                </div>
                <div class="col-md-4 text-md-end text-start">
                    <h6 class="fw-bold text-white mb-2">Connect Digitally</h6>
                    <div class="d-flex justify-content-md-end gap-3 mb-3">
                        ${block.socials.map(soc => `
                        <a href="${soc.url}" class="text-white text-decoration-none bg-secondary bg-opacity-25 rounded-circle d-inline-flex align-items-center justify-content-center shadow-sm" style="width: 40px; height: 40px;">
                            <i class="bi bi-${soc.platform.toLowerCase() === 'twitter' ? 'twitter-x' : soc.platform.toLowerCase()}"></i>
                        </a>`).join('')}
                    </div>
                </div>
            </div>
            <div class="border-top border-secondary mt-4 pt-4 text-center">
                <p class="text-secondary small mb-0">${block.copyright}</p>
            </div>
        </div>
    </footer>
`;
        break;
      }
    }
  });

  content += `
@endsection
`;
  return content;
}
