import { WebDesignConfig, Block, Page } from '../types';

// Map icon names to Bootstrap Icons or Lucide CSS classes for accurate Laravel blade styling
export function getBootstrapIconClass(icon: string): string {
  const iconMap: Record<string, string> = {
    Sparkles: 'bi-stars',
    Database: 'bi-database',
    Cpu: 'bi-cpu',
    Shield: 'bi-shield-check',
    Zap: 'bi-lightning-charge-fill',
    Box: 'bi-box-seam',
    ShoppingCart: 'bi-cart4',
    Users: 'bi-people-fill',
    Heart: 'bi-heart-fill',
    Star: 'bi-star-fill',
    Globe: 'bi-globe',
    TrendingUp: 'bi-graph-up-arrow'
  };
  return iconMap[icon] || 'bi-bookmark-star-fill';
}

export function generateLaravelFiles(config: WebDesignConfig): Record<string, string> {
  const files: Record<string, string> = {};
  const activePage = config.pages.find(p => p.id === config.activePageId) || config.pages[0];
  const primaryColor = config.colorPalette.primary;
  const secondaryColor = config.colorPalette.secondary;
  const darkColor = config.colorPalette.dark;
  const lightColor = config.colorPalette.light;
  
  // 1. web.php Routing
  files['routes/web.php'] = `<?php

use App\\Http\\Controllers\\HomeController;
use Illuminate\\Support\\Facades\\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your CMS website application.
| Generated by LaraBoot Visual Builder CMS.
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
${config.pages.filter(p => p.id !== 'home').map(p => {
  return `Route::get('/${p.slug}', [HomeController::class, '${p.slug}'])->name('${p.id}');`;
}).join('\n')}
`;

  // 2. HomeController.php (Strict Layered Dependency Injection: Controller -> Service -> Interface -> Repository)
  files['app/Http/Controllers/HomeController.php'] = `<?php

namespace App\\Http\\Controllers;

use Illuminate\\Http\\Request;
use App\\Services\\BlogPostService;
use App\\Services\\ProductService;
${config.enableAuditTrail ? 'use App\\Services\\AuditTrailService;' : ''}
${config.enableDynamicMenu ? 'use App\\Services\\MenuService;' : ''}

class HomeController extends Controller
{
    protected $blogService;
    protected $productService;
    ${config.enableAuditTrail ? 'protected $auditService;' : ''}
    ${config.enableDynamicMenu ? 'protected $menuService;' : ''}

    /**
     * Dependency Injected from Service Layer directly, fully satisfying architectural guidelines.
     */
    public function __construct(
        BlogPostService $blogService, 
        ProductService $productService
        ${config.enableAuditTrail ? ', AuditTrailService $auditService' : ''}
        ${config.enableDynamicMenu ? ', MenuService $menuService' : ''}
    ) {
        $this->blogService = $blogService;
        $this->productService = $productService;
        ${config.enableAuditTrail ? '$this->auditService = $auditService;' : ''}
        ${config.enableDynamicMenu ? '$this->menuService = $menuService;' : ''}
    }

    /**
     * Display the CMS dynamically computed landing page.
     */
    public function index()
    {
        // Controller delegates business logic entirely to the Layered Service
        $blogs = $this->blogService->getLatestPosts();
        $products = $this->productService->getAvailableProducts();
        $auditLogs = ${config.enableAuditTrail ? '$this->auditService->getRecentActivityLogs(5)' : 'collect()'};
        $menuModules = ${config.enableDynamicMenu ? '$this->menuService->getDynamicMenuStructure()' : 'collect()'};

        // Log page visit via Audit Trail system
        if (${config.enableAuditTrail ? 'true' : 'false'}) {
            $this->auditService->logActivity('PAGE_VIEW', 'Page', 1, null, ['slug' => 'index_portal']);
        }

        return view('welcome', [
            'projectName' => '${config.projectName}',
            'blogs' => $blogs,
            'products' => $products,
            'auditLogs' => $auditLogs,
            'menuModules' => $menuModules,
            'colorScheme' => [
                'primary' => '${primaryColor}',
                'secondary' => '${secondaryColor}'
            ]
        ]);
    }
${config.pages.filter(p => p.id !== 'home').map(p => `
    /**
     * Display the ${p.title} page.
     */
    public function ${p.slug}()
    {
        $menuModules = ${config.enableDynamicMenu ? '$this->menuService->getDynamicMenuStructure()' : 'collect()'};
        
        if (${config.enableAuditTrail ? 'true' : 'false'}) {
            $this->auditService->logActivity('PAGE_VIEW', 'Page', 2, null, ['slug' => '${p.slug}']);
        }

        return view('pages.${p.slug}', [
            'projectName' => '${config.projectName}',
            'menuModules' => $menuModules,
            'colorScheme' => [
                'primary' => '${primaryColor}',
                'secondary' => '${secondaryColor}'
            ]
        ]);
    }
`).join('\n')}
}
`;

  // 3. Blog & Product Models
  files['app/Models/BlogPost.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class BlogPost extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'category',
        'author',
        'image_url'
    ];
}
`;

  files['app/Models/Product.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'price',
        'description',
        'image_url',
        'in_stock'
    ];

    protected $casts = [
        'in_stock' => 'boolean',
        'price' => 'decimal:2'
    ];
}
`;

  if (config.enableAuditTrail) {
    files['app/Models/AuditTrail.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class AuditTrail extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'action',
        'model',
        'model_id',
        'old_values',
        'new_values',
        'ip_address',
        'user_agent'
    ];

    protected $casts = [
        'old_values' => 'array',
        'new_values' => 'array',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
`;
  }

  if (config.enableDynamicMenu) {
    files['app/Models/MenuModule.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class MenuModule extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'icon', 'sequence', 'is_active'];

    public function submodules()
    {
        return $this->hasMany(MenuSubmodule::class, 'module_id');
    }
}
`;

    files['app/Models/MenuSubmodule.php'] = `<?php

namespace App\\Models;

use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;
use Illuminate\\Database\\Eloquent\\Model;

class MenuSubmodule extends Model
{
    use HasFactory;

    protected $fillable = ['module_id', 'name', 'slug', 'icon', 'url', 'sequence', 'permission_name', 'is_active'];

    public function module()
    {
        return $this->belongsTo(MenuModule::class, 'module_id');
    }
}
`;
  }

  // 3b. Repository Interfaces (Contracts for loose coupling)
  files['app/Repositories/Contracts/BaseRepositoryInterface.php'] = `<?php

namespace App\\Repositories\\Contracts;

interface BaseRepositoryInterface
{
    public function all();
    public function find($id);
    public function create(array $data);
    public function update($id, array $data);
    public function delete($id);
}
`;

  files['app/Repositories/Contracts/BlogPostRepositoryInterface.php'] = `<?php

namespace App\\Repositories\\Contracts;

interface BlogPostRepositoryInterface extends BaseRepositoryInterface
{
    public function getLatest($limit = 10);
    public function findBySlug($slug);
}
`;

  files['app/Repositories/Contracts/ProductRepositoryInterface.php'] = `<?php

namespace App\\Repositories\\Contracts;

interface ProductRepositoryInterface extends BaseRepositoryInterface
{
    public function getInStock();
}
`;

  if (config.enableAuditTrail) {
    files['app/Repositories/Contracts/AuditTrailRepositoryInterface.php'] = `<?php

namespace App\\Repositories\\Contracts;

interface AuditTrailRepositoryInterface extends BaseRepositoryInterface
{
    public function getLatestLogs($limit = 50);
}
`;
  }

  if (config.enableDynamicMenu) {
    files['app/Repositories/Contracts/MenuRepositoryInterface.php'] = `<?php

namespace App\\Repositories\\Contracts;

interface MenuRepositoryInterface extends BaseRepositoryInterface
{
    public function getActiveMenuWithSubmodules();
}
`;
  }

  // 3c. Eloquent Repository Implementations
  files['app/Repositories/Eloquent/BaseRepository.php'] = `<?php

namespace App\\Repositories\\Eloquent;

use App\\Repositories\\Contracts\\BaseRepositoryInterface;
use Illuminate\\Database\\Eloquent\\Model;

abstract class BaseRepository implements BaseRepositoryInterface
{
    protected $model;

    public function __construct(Model $model)
    {
        $this->model = $model;
    }

    public function all()
    {
        return $this->model->all();
    }

    public function find($id)
    {
        return $this->model->find($id);
    }

    public function create(array $data)
    {
        return $this->model->create($data);
    }

    public function update($id, array $data)
    {
        $record = $this->find($id);
        if ($record) {
            $record->update($data);
            return $record;
        }
        return null;
    }

    public function delete($id)
    {
        $record = $this->find($id);
        if ($record) {
            return $record->delete();
        }
        return false;
    }
}
`;

  files['app/Repositories/Eloquent/BlogPostRepository.php'] = `<?php

namespace App\\Repositories\\Eloquent;

use App\\Models\\BlogPost;
use App\\Repositories\\Contracts\\BlogPostRepositoryInterface;

class BlogPostRepository extends BaseRepository implements BlogPostRepositoryInterface
{
    public function __construct(BlogPost $model)
    {
        parent::__construct($model);
    }

    public function getLatest($limit = 10)
    {
        return $this->model->orderBy('created_at', 'desc')->take($limit)->get();
    }

    public function findBySlug($slug)
    {
        return $this->model->where('slug', $slug)->first();
    }
}
`;

  files['app/Repositories/Eloquent/ProductRepository.php'] = `<?php

namespace App\\Repositories\\Eloquent;

use App\\Models\\Product;
use App\\Repositories\\Contracts\\ProductRepositoryInterface;

class ProductRepository extends BaseRepository implements ProductRepositoryInterface
{
    public function __construct(Product $model)
    {
        parent::__construct($model);
    }

    public function getInStock()
    {
        return $this->model->where('in_stock', true)->get();
    }
}
`;

  if (config.enableAuditTrail) {
    files['app/Repositories/Eloquent/AuditTrailRepository.php'] = `<?php

namespace App\\Repositories\\Eloquent;

use App\\Models\\AuditTrail;
use App\\Repositories\\Contracts\\AuditTrailRepositoryInterface;

class AuditTrailRepository extends BaseRepository implements AuditTrailRepositoryInterface
{
    public function __construct(AuditTrail $model)
    {
        parent::__construct($model);
    }

    public function getLatestLogs($limit = 50)
    {
        return $this->model->orderBy('created_at', 'desc')->take($limit)->get();
    }
}
`;
  }

  if (config.enableDynamicMenu) {
    files['app/Repositories/Eloquent/MenuRepository.php'] = `<?php

namespace App\\Repositories\\Eloquent;

use App\\Models\\MenuModule;
use App\\Repositories\\Contracts\\MenuRepositoryInterface;

class MenuRepository extends BaseRepository implements MenuRepositoryInterface
{
    public function __construct(MenuModule $model)
    {
        parent::__construct($model);
    }

    public function getActiveMenuWithSubmodules()
    {
        return $this->model->with(['submodules' => function ($query) {
            $query->where('is_active', true)->orderBy('sequence');
        }])->where('is_active', true)->orderBy('sequence')->get();
    }
}
`;
  }

  // 3d. Service Classes (Business Logic Layer)
  files['app/Services/BlogPostService.php'] = `<?php

namespace App\\Services;

use App\\Repositories\\Contracts\\BlogPostRepositoryInterface;
${config.enableAuditTrail ? 'use App\\Repositories\\Contracts\\AuditTrailRepositoryInterface;' : ''}
use Illuminate\\Support\\Facades\\Auth;

class BlogPostService
{
    protected $blogRepo;
    protected $auditRepo;

    public function __construct(
        BlogPostRepositoryInterface $blogRepo
        ${config.enableAuditTrail ? ', AuditTrailRepositoryInterface $auditRepo = null' : ''}
    ) {
        $this->blogRepo = $blogRepo;
        ${config.enableAuditTrail ? '$this->auditRepo = $auditRepo;' : ''}
    }

    public function getLatestPosts($limit = 10)
    {
        return $this->blogRepo->getLatest($limit);
    }

    public function getPostBySlug($slug)
    {
        return $this->blogRepo->findBySlug($slug);
    }

    public function createPost(array $data)
    {
        $post = $this->blogRepo->create($data);

        if ($post && $this->auditRepo) {
            $this->auditRepo->create([
                'user_id' => Auth::id() ?? 1,
                'action' => 'CREATE_BLOG',
                'model' => 'BlogPost',
                'model_id' => $post->id,
                'new_values' => $post->toArray(),
                'ip_address' => request()->ip(),
                'user_agent' => request()->userAgent()
            ]);
        }

        return $post;
    }
}
`;

  files['app/Services/ProductService.php'] = `<?php

namespace App\\Services;

use App\\Repositories\\Contracts\\ProductRepositoryInterface;
${config.enableAuditTrail ? 'use App\\Repositories\\Contracts\\AuditTrailRepositoryInterface;' : ''}
use Illuminate\\Support\\Facades\\Auth;

class ProductService
{
    protected $productRepo;
    protected $auditRepo;

    public function __construct(
        ProductRepositoryInterface $productRepo
        ${config.enableAuditTrail ? ', AuditTrailRepositoryInterface $auditRepo = null' : ''}
    ) {
        $this->productRepo = $productRepo;
        ${config.enableAuditTrail ? '$this->auditRepo = $auditRepo;' : ''}
    }

    public function getAvailableProducts()
    {
        return $this->productRepo->getInStock();
    }

    public function createProduct(array $data)
    {
        $product = $this->productRepo->create($data);

        if ($product && $this->auditRepo) {
            $this->auditRepo->create([
                'user_id' => Auth::id() ?? 1,
                'action' => 'CREATE_PRODUCT',
                'model' => 'Product',
                'model_id' => $product->id,
                'new_values' => $product->toArray(),
                'ip_address' => request()->ip(),
                'user_agent' => request()->userAgent()
            ]);
        }

        return $product;
    }
}
`;

  if (config.enableAuditTrail) {
    files['app/Services/AuditTrailService.php'] = `<?php

namespace App\\Services;

use App\\Repositories\\Contracts\\AuditTrailRepositoryInterface;

class AuditTrailService
{
    protected $auditRepo;

    public function __construct(AuditTrailRepositoryInterface $auditRepo)
    {
        $this->auditRepo = $auditRepo;
    }

    public function getRecentActivityLogs($limit = 50)
    {
        return $this->auditRepo->getLatestLogs($limit);
    }

    public function logActivity($action, $modelName, $modelId, $oldVals = null, $newVals = null)
    {
        return $this->auditRepo->create([
            'user_id' => auth()->id() ?? 1,
            'action' => $action,
            'model' => $modelName,
            'model_id' => $modelId,
            'old_values' => $oldVals,
            'new_values' => $newVals,
            'ip_address' => request()->ip(),
            'user_agent' => request()->userAgent()
        ]);
    }
}
`;
  }

  if (config.enableDynamicMenu) {
    files['app/Services/MenuService.php'] = `<?php

namespace App\\Services;

use App\\Repositories\\Contracts\\MenuRepositoryInterface;

class MenuService
{
    protected $menuRepo;

    public function __construct(MenuRepositoryInterface $menuRepo)
    {
        $this->menuRepo = $menuRepo;
    }

    public function getDynamicMenuStructure()
    {
        return $this->menuRepo->getActiveMenuWithSubmodules();
    }
}
`;
  }

  // 3e. RepositoryServiceProvider.php - Loose Coupling Container Registrations
  files['app/Providers/RepositoryServiceProvider.php'] = `<?php

namespace App\\Providers;

use Illuminate\\Support\\ServiceProvider;

use App\\Repositories\\Contracts\\BlogPostRepositoryInterface;
use App\\Repositories\\Eloquent\\BlogPostRepository;
use App\\Repositories\\Contracts\\ProductRepositoryInterface;
use App\\Repositories\\Eloquent\\ProductRepository;
${config.enableAuditTrail ? "use App\\\\Repositories\\\\Contracts\\\\AuditTrailRepositoryInterface;\nuse App\\\\Repositories\\\\Eloquent\\\\AuditTrailRepository;" : ''}
${config.enableDynamicMenu ? "use App\\\\Repositories\\\\Contracts\\\\MenuRepositoryInterface;\nuse App\\\\Repositories\\\\Eloquent\\\\MenuRepository;" : ''}

class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Register Interface-to-Repository bindings inside the Container.
     */
    public function register(): void
    {
        $this->app->bind(BlogPostRepositoryInterface::class, BlogPostRepository::class);
        $this->app->bind(ProductRepositoryInterface::class, ProductRepository::class);
        
        ${config.enableAuditTrail ? '$this->app->bind(AuditTrailRepositoryInterface::class, AuditTrailRepository::class);' : ''}
        ${config.enableDynamicMenu ? '$this->app->bind(MenuRepositoryInterface::class, MenuRepository::class);' : ''}
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
}
`;

  // 4. database/migrations/xxx_create_cms_tables.php
  files['database/migrations/2026_06_16_000000_create_cms_tables.php'] = `<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

return new class extends Migration
{
    /**
     * Run the migrations for static and dynamic cms bindings.
     */
    public function up(): void
    {
        Schema::create('blog_posts', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->text('excerpt');
            $table->text('body');
            $table->string('category')->nullable();
            $table->string('author')->nullable();
            $table->string('image_url')->nullable();
            $table->timestamps();
        });

        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->unique();
            $table->decimal('price', 10, 2);
            $table->text('description');
            $table->string('image_url')->nullable();
            $table->boolean('in_stock')->default(true);
            $table->timestamps();
        });

        ${config.enableSpatiePermissions ? `
        // Spatie standard tables structure
        Schema::create('roles', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('guard_name');
            $table->timestamps();
            $table->unique(['name', 'guard_name']);
        });

        Schema::create('permissions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('guard_name');
            $table->timestamps();
            $table->unique(['name', 'guard_name']);
        });

        Schema::create('model_has_roles', function (Blueprint $table) {
            $table->unsignedBigInteger('role_id');
            $table->string('model_type');
            $table->unsignedBigInteger('model_id');
            $table->index(['model_id', 'model_type'], 'model_has_roles_model_id_model_type_index');
            $table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
            $table->primary(['role_id', 'model_id', 'model_type'], 'model_has_roles_role_model_type_primary');
        });

        Schema::create('model_has_permissions', function (Blueprint $table) {
            $table->unsignedBigInteger('permission_id');
            $table->string('model_type');
            $table->unsignedBigInteger('model_id');
            $table->index(['model_id', 'model_type'], 'model_has_permissions_model_id_model_type_index');
            $table->foreign('permission_id')->references('id')->on('permissions')->onDelete('cascade');
            $table->primary(['permission_id', 'model_id', 'model_type'], 'model_has_permissions_permission_model_type_primary');
        });

        Schema::create('role_has_permissions', function (Blueprint $table) {
            $table->unsignedBigInteger('permission_id');
            $table->unsignedBigInteger('role_id');
            $table->foreign('permission_id')->references('id')->on('permissions')->onDelete('cascade');
            $table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
            $table->primary(['permission_id', 'role_id']);
        });
        ` : ''}

        ${config.enableAuditTrail ? `
        // System logs / Audit Trails
        Schema::create('audit_trails', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->string('action');
            $table->string('model')->nullable();
            $table->unsignedBigInteger('model_id')->nullable();
            $table->text('old_values')->nullable();
            $table->text('new_values')->nullable();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->timestamps();
        });
        ` : ''}

        ${config.enableDynamicMenu ? `
        // Dynamic modules and submodules
        Schema::create('menu_modules', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->unique();
            $table->string('icon')->nullable();
            $table->integer('sequence')->default(0);
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });

        Schema::create('menu_submodules', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('module_id');
            $table->string('name');
            $table->string('slug');
            $table->string('icon')->nullable();
            $table->string('url');
            $table->integer('sequence')->default(0);
            $table->string('permission_name')->nullable();
            $table->boolean('is_active')->default(true);
            $table->timestamps();
            $table->foreign('module_id')->references('id')->on('menu_modules')->onDelete('cascade');
        });
        ` : ''}
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('menu_submodules');
        Schema::dropIfExists('menu_modules');
        Schema::dropIfExists('audit_trails');
        Schema::dropIfExists('role_has_permissions');
        Schema::dropIfExists('model_has_permissions');
        Schema::dropIfExists('model_has_roles');
        Schema::dropIfExists('permissions');
        Schema::dropIfExists('roles');
        Schema::dropIfExists('blog_posts');
        Schema::dropIfExists('products');
    }
};
`;

  // 5. database/seeders/DatabaseSeeder.php
  files['database/seeders/DatabaseSeeder.php'] = `<?php

namespace Database\\Seeders;

use Illuminate\\Database\\Seeder;
use App\\Models\\BlogPost;
use App\\Models\\Product;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database with LaraBoot CMS mock records.
     */
    public function run(): void
    {
        // Seeding interactive blog posts
        ${(config.blogModels || []).map(b => `
        BlogPost::create([
            'title' => '${(b.title || '').replace(/'/g, "\\'")}',
            'slug' => '${b.slug || ''}',
            'excerpt' => '${(b.excerpt || '').replace(/'/g, "\\'")}',
            'body' => '${(b.body || '').replace(/'/g, "\\'")}',
            'category' => '${(b.category || '').replace(/'/g, "\\'")}',
            'author' => '${(b.author || '').replace(/'/g, "\\'")}',
            'image_url' => '${(b.imageUrl || '').replace(/'/g, "\\'")}'
        ]);`).join('\n')}

        // Seeding products
        ${(config.productModels || []).map(p => {
          const rawPrice = p.price != null ? String(p.price) : '0';
          const cleanPrice = parseFloat(rawPrice.replace(/[^0-9.]/g, '')) || 0.00;
          return `
        Product::create([
            'name' => '${(p.name || '').replace(/'/g, "\\'")}',
            'slug' => '${p.slug || ''}',
            'price' => ${cleanPrice.toFixed(2)},
            'description' => '${(p.description || '').replace(/'/g, "\\'")}',
            'image_url' => '${(p.imageUrl || '').replace(/'/g, "\\'")}',
            'in_stock' => ${p.inStock ? 'true' : 'false'}
        ]);`;
        }).join('\n')}

        // Seed Spatie roles and permissions
        ${config.enableSpatiePermissions ? `
        // Create permissions
        $permsMap = [];
        ${(config.spatiePermissions || [
            { id: 'p1', name: 'blog_posts.create' },
            { id: 'p2', name: 'blog_posts.read' },
            { id: 'p3', name: 'blog_posts.update' },
            { id: 'p4', name: 'blog_posts.delete' },
            { id: 'p5', name: 'products.create' },
            { id: 'p6', name: 'products.read' },
            { id: 'p7', name: 'products.update' },
            { id: 'p8', name: 'products.delete' }
        ]).map((p, idx) => `
        $permId_${idx + 1} = \\Illuminate\\Support\\Facades\\DB::table('permissions')->insertGetId([
            'name' => '${p.name}',
            'guard_name' => 'web',
            'created_at' => now(),
            'updated_at' => now()
        ]);
        $permsMap['${p.name}'] = $permId_${idx + 1};
        `).join('\n')}

        // Create roles and attach permissions
        ${(config.spatieRoles || [
            { id: 'r1', name: 'Administrator', permissions: ['blog_posts.create', 'blog_posts.read', 'blog_posts.update', 'blog_posts.delete', 'products.create', 'products.read', 'products.update', 'products.delete'] },
            { id: 'r2', name: 'Editor', permissions: ['blog_posts.create', 'blog_posts.read', 'blog_posts.update', 'products.create', 'products.read'] },
            { id: 'r3', name: 'User', permissions: ['blog_posts.read', 'products.read'] }
        ]).map((role, idx) => `
        $roleId_${idx + 1} = \\Illuminate\\Support\\Facades\\DB::table('roles')->insertGetId([
            'name' => '${role.name}',
            'guard_name' => 'web',
            'created_at' => now(),
            'updated_at' => now()
        ]);

        // Attach permissions to role: ${role.name}
        ${role.permissions.map(permName => `
        if (isset($permsMap['${permName}'])) {
            \\Illuminate\\Support\\Facades\\DB::table('role_has_permissions')->insert([
                'permission_id' => $permsMap['${permName}'],
                'role_id' => $roleId_${idx + 1}
            ]);
        }
        `).join('\n')}
        `).join('\n')}
        ` : ''}

        // Seed dynamic menu modules and submodules
        ${config.enableDynamicMenu ? `
        ${(config.modules || []).map((mod, modIdx) => `
        $moduleId = \\Illuminate\\Support\\Facades\\DB::table('menu_modules')->insertGetId([
            'name' => '${mod.name.replace(/'/g, "\\'")}',
            'slug' => '${mod.slug}',
            'icon' => '${mod.icon}',
            'sequence' => ${mod.order},
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        ${(mod.submodules || []).map((sub, subIdx) => `
        \\Illuminate\\Support\\Facades\\DB::table('menu_submodules')->insert([
            'module_id' => $moduleId,
            'name' => '${sub.name.replace(/'/g, "\\'")}',
            'slug' => '${sub.slug}',
            'url' => '${sub.url}',
            'icon' => '${sub.icon}',
            'sequence' => ${sub.order},
            'permission_name' => '${sub.permission || ''}',
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now()
        ]);`).join('\n')}
        `).join('\n')}
        ` : ''}

        // Seeding audit trails
        ${config.enableAuditTrail ? `
        \\Illuminate\\Support\\Facades\\DB::table('audit_trails')->insert([
            'user_id' => 1,
            'action' => 'SYSTEM_INIT',
            'model' => 'System',
            'model_id' => 1,
            'new_values' => json_encode(['status' => 'LaraBoot Clean 5-Tier Architecture Loaded']),
            'ip_address' => '127.0.0.1',
            'user_agent' => 'LaraBoot Visual Compiler',
            'created_at' => now(),
            'updated_at' => now()
        ]);
        ` : ''}
    }
}
`;

  // 6. resources/views/layouts/app.blade.php (Main Master Page supporting Landing, Corporate, and Admin Sidebar Templates)
  if (config.bladeTemplateStyle === 'admin_dashboard') {
    files['resources/views/layouts/app.blade.php'] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Enterprise Workspace - {{ $projectName ?? '${config.projectName}' }}</title>
    
    <!-- Bootstrap 5 CSS & Font -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    
    <style>
        :root {
            --bs-primary: ${primaryColor};
            --bs-secondary: ${secondaryColor};
            --bs-primary-rgb: ${hexToRgb(primaryColor)};
            --cms-dark: ${darkColor};
            --cms-light: ${lightColor};
            --sidebar-width: 260px;
        }
        body {
            font-family: 'Space Grotesk', -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background-color: #f3f4f6;
            color: var(--cms-dark);
            overflow-x: hidden;
        }
        .admin-sidebar {
            width: var(--sidebar-width);
            height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #111827; /* Tailwind Charcoal Gray 900 */
            z-index: 1000;
            transition: all 0.3s;
            border-right: 1px solid #1f2937;
        }
        .admin-main {
            margin-left: var(--sidebar-width);
            min-height: 100vh;
            transition: all 0.3s;
        }
        .sidebar-brand {
            padding: 1.5rem 1.25rem;
            color: #fff;
            border-bottom: 1px solid #1f2937;
        }
        .sidebar-menu {
            padding: 1rem 0;
            list-style: none;
            margin: 0;
        }
        .menu-header {
            padding: 0.5rem 1.5rem;
            font-size: 0.7rem;
            text-transform: uppercase;
            font-weight: 700;
            letter-spacing: 0.05em;
            color: #6b7280;
        }
        .menu-link {
            display: flex;
            align-items: center;
            padding: 0.65rem 1.5rem;
            color: #9ca3af;
            text-decoration: none;
            font-size: 0.85rem;
            transition: all 0.2s;
            border-left: 3px solid transparent;
        }
        .menu-link:hover, .menu-link.active {
            color: #fff;
            background-color: #1f2937;
            border-left-color: var(--bs-primary);
        }
        .sub-menu {
            list-style: none;
            padding-left: 2.5rem;
            margin: 0.25rem 0 0.75rem 0;
        }
        .sub-link {
            display: block;
            padding: 0.35rem 0;
            color: #9ca3af;
            text-decoration: none;
            font-size: 0.8rem;
            transition: color 0.2s;
        }
        .sub-link:hover {
            color: #fff;
        }
        .topbar {
            height: 65px;
            background-color: #ffffff;
            border-bottom: 1px solid #e5e7eb;
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 1.5rem;
        }
        .badge-role {
            background-color: rgba(${hexToRgb(primaryColor)}, 0.1);
            color: var(--bs-primary);
            border: 1px solid rgba(${hexToRgb(primaryColor)}, 0.2);
            font-size: 0.75rem;
            padding: 0.25rem 0.65rem;
            border-radius: 50px;
        }
        .architecture-stamp {
            font-size: 0.7rem;
            font-weight: 600;
            letter-spacing: 0.05em;
            color: #10b981; /* Emerald green */
            background-color: rgba(16, 185, 129, 0.1);
            padding: 0.15rem 0.4rem;
            border-radius: 4px;
            text-transform: uppercase;
        }
    </style>
</head>
<body>

    <!-- Responsive Dark Sidebar Menu (Dynamic Modules Setup) -->
    <div class="admin-sidebar shadow-lg">
        <div class="sidebar-brand">
            <h5 class="mb-0 fw-bold text-white flex items-center gap-2">
                <i class="bi bi-shield-lock-fill text-primary"></i> ${config.projectName}
            </h5>
            <span class="text-secondary small fw-medium">Layered Architecture</span>
        </div>
        
        <ul class="sidebar-menu">
            <li class="menu-header">General Nav</li>
            <li>
                <a href="{{ route('home') }}" class="menu-link active">
                    <i class="bi bi-speedometer2 me-2 text-primary"></i> Dynamic Workspace
                </a>
            </li>

            <!-- Dynamic Admin Modules loop -->
            @isset($menuModules)
                @if(count($menuModules) > 0)
                    @foreach($menuModules as $mod)
                        <li class="menu-header mt-3"><i class="bi bi-app-indicator me-1"></i> {{ $mod->name }}</li>
                        @foreach($mod->submodules as $sub)
                            <li>
                                <a href="{{ $sub->url }}" class="menu-link gap-2">
                                    <i class="bi bi-arrow-right-short text-secondary"></i> {{ $sub->name }}
                                </a>
                            </li>
                        @endforeach
                    @endforeach
                @else
                    <!-- Fallback if database is not migrated yet -->
                    <li class="menu-header mt-3">Pre-Config Modules</li>
                    <li>
                        <a href="#cms" class="menu-link"><i class="bi bi-globe me-2 text-primary"></i> CMS Core</a>
                        <ul class="sub-menu">
                            <li><a href="#pages" class="sub-link">Web Pages Router</a></li>
                            <li><a href="#blocks" class="sub-link">Section Blocks Manager</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#security" class="menu-link"><i class="bi bi-shield-check me-2 text-success"></i> Security Panel</a>
                        <ul class="sub-menu">
                            <li><a href="#roles" class="sub-link">Spatie Role Manager</a></li>
                            <li><a href="#permissions" class="sub-link">Spatie Permissions</a></li>
                        </ul>
                    </li>
                @endif
            @endisset
        </ul>
    </div>

    <!-- Main Workspace Frame -->
    <div class="admin-main">
        <header class="topbar sticky-top shadow-xs">
            <div class="d-flex align-items-center gap-3">
                <span class="architecture-stamp">Layered MVC (5-Tier) Enforced</span>
                <span class="badge bg-light text-dark border small py-1.5 px-3"><i class="bi bi-hdd-fill text-secondary me-1.5"></i> SQLite DB: connected</span>
            </div>
            
            <div class="d-flex align-items-center gap-3">
                <div class="dropdown">
                    <button class="btn btn-sm btn-light border dropdown-toggle" type="button" data-bs-toggle="dropdown">
                        <i class="bi bi-person-badge-fill text-primary me-1"></i> Active Role: <strong>Administrator</strong>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end shadow">
                        <li><a class="dropdown-item" href="#">Spatie Administrator</a></li>
                        <li><a class="dropdown-item" href="#">Spatie Content Manager</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Logout Session</a></li>
                    </ul>
                </div>
            </div>
        </header>

        <main class="p-4 p-md-5">
            @yield('content')
        </main>
    </div>

    <!-- Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
`;
  } else if (config.bladeTemplateStyle === 'laravel_breeze') {
    files['resources/views/layouts/app.blade.php'] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Dashboard - {{ $projectName ?? '${config.projectName}' }}</title>
    
    <!-- AlpineJS & Tailwind CSS CDN for exact Breeze emulation -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">

    <script>
        tailwind.config = {
            theme: {
                extend: {
                    fontFamily: {
                        sans: ['Instrument Sans', 'sans-serif'],
                    },
                    colors: {
                        brand: {
                            primary: '${primaryColor}',
                            secondary: '${secondaryColor}',
                        }
                    }
                }
            }
        }
    </script>
</head>
<body class="bg-gray-100 text-gray-900 font-sans dynamic-menu-active">
    <div class="min-h-screen bg-gray-50 flex flex-col">
        <!-- Breeze Minimalist Navbar -->
        <nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div class="flex justify-between h-16">
                    <div class="flex">
                        <!-- Logo -->
                        <div class="shrink-0 flex items-center">
                            <a href="{{ route('home') }}" class="flex items-center gap-2 font-bold text-xl text-gray-800">
                                <svg class="w-9 h-9 text-red-500 fill-current" viewBox="0 0 62 65" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M61.854 10.354l-11-11a1 1 0 0 0-1.414 0L38.44 10.354l23.414 23.414 11-11a1 1 0 0 0 0-1.414zM24.44 24.354L1 47.794V61h13.206l23.44-23.44-13.206-13.206z" />
                                </svg>
                                <span class="bg-gradient-to-r from-red-600 to-amber-500 bg-clip-text text-transparent">${config.projectName}</span>
                            </a>
                        </div>

                        <!-- Navigation Links -->
                        <div class="hidden space-x-8 sm:-my-px sm:ms-10 sm:flex">
                            <a href="{{ route('home') }}" class="inline-flex items-center px-1 pt-1 border-b-2 border-red-500 text-sm font-semibold leading-5 text-gray-900 focus:outline-none transition duration-150 ease-in-out">
                                Dashboard
                            </a>
                            <!-- Dynamic menu items in Breeze style -->
                            @isset($menuModules)
                                @foreach($menuModules as $mod)
                                    @foreach($mod->submodules as $sub)
                                        <a href="{{ $sub->url }}" class="inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium leading-5 text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none transition duration-150 ease-in-out">
                                            {{ $sub->name }}
                                        </a>
                                    @endforeach
                                @endforeach
                            @endisset
                        </div>
                    </div>

                    <!-- Settings Dropdown -->
                    <div class="hidden sm:flex sm:items-center sm:ms-6">
                        <div x-data="{ dropdownOpen: false }" class="relative">
                            <button @click="dropdownOpen = !dropdownOpen" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-semibold rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                                <div><i class="bi bi-person-circle text-gray-400 mr-1"></i> Taylor Otwell</div>
                                <div class="ms-1">
                                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                            </button>

                            <!-- Dropdown content -->
                            <div x-show="dropdownOpen" @click.away="dropdownOpen = false" class="absolute right-0 z-50 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" style="display: none;">
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Your Profile</a>
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Breeze Settings</a>
                                <hr class="border-gray-100" />
                                <a href="#" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 font-semibold">Logout</a>
                            </div>
                        </div>
                    </div>

                    <!-- Hamburger -->
                    <div class="-me-2 flex items-center sm:hidden">
                        <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                                <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Responsive Navigation Menu -->
            <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden bg-white border-t border-gray-100">
                <div class="pt-2 pb-3 space-y-1">
                    <a href="{{ route('home') }}" class="block ps-3 pe-4 py-2 border-l-4 border-red-500 text-base font-medium text-red-700 bg-red-50 focus:outline-none transition duration-150 ease-in-out">
                        Dashboard
                    </a>
                    @isset($menuModules)
                        @foreach($menuModules as $mod)
                            @foreach($mod->submodules as $sub)
                                <a href="{{ $sub->url }}" class="block ps-3 pe-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none transition duration-150 ease-in-out">
                                    {{ $sub->name }}
                                </a>
                            @endforeach
                        @endforeach
                    @endisset
                </div>
            </div>
        </nav>

        <!-- Breeze Core Header Area -->
        <header class="bg-white shadow">
            <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 flex justify-between items-center">
                <h1 class="text-xl font-semibold leading-tight text-gray-800">
                    Laravel Breeze Starter Kit Portal
                </h1>
                <span class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-800">
                    <span class="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                    Authenticated (Role: Developer)
                </span>
            </div>
        </header>

        <!-- Page Content -->
        <main class="flex-grow py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <!-- Breeze Card Container -->
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg border border-gray-200">
                    <div class="p-6 text-gray-900">
                        @yield('content')
                    </div>
                </div>
            </div>
        </main>
        
        <!-- Breeze Footer -->
        <footer class="bg-white border-t border-gray-100 py-6">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-xs text-gray-500">
                &copy; {{ date('Y') }} ${config.projectName}. Build powered by Laravel Breeze &amp; LaraBoot Architect.
            </div>
        </footer>
    </div>
</body>
</html>
`;
  } else if (config.bladeTemplateStyle === 'laravel_ui') {
    files['resources/views/layouts/app.blade.php'] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Laravel UI Portal - {{ $projectName ?? '${config.projectName}' }}</title>
    
    <!-- Bootstrap 5 CSS & Font (Traditional laravel/ui with bootstrap) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    
    <style>
        :root {
            --bs-primary: ${primaryColor};
            --bs-secondary: ${secondaryColor};
            --bs-primary-rgb: ${hexToRgb(primaryColor)};
        }
        body {
            font-family: 'Nunito', -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background-color: #f8fafc;
            color: #333333;
        }
        .navbar-laravel {
            background-color: #ffffff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.04);
            border-bottom: 1px solid #e5e7eb;
        }
        .auth-card {
            border: 1px solid #dfdfdf;
            border-radius: 4px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        }
        .auth-card .card-header {
            background-color: #f1f5f9;
            border-bottom: 1px solid #dfdfdf;
            font-weight: 600;
        }
    </style>
</head>
<body>
    <div id="app">
        <!-- Traditional Laravel UI Bootstrap Header -->
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel py-3">
            <div class="container">
                <a class="navbar-brand fw-bold text-primary" href="{{ url('/') }}">
                    <i class="bi bi-bootstrap-fill me-1.5"></i> {{ $projectName ?? '${config.projectName}' }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active fw-semibold" href="{{ route('home') }}">Dashboard Home</a>
                        </li>
                        @isset($menuModules)
                            @foreach($menuModules as $mod)
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                                        {{ $mod->name }}
                                    </a>
                                    <ul class="dropdown-menu">
                                        @foreach($mod->submodules as $sub)
                                            <li><a class="dropdown-item" href="{{ $sub->url }}">{{ $sub->name }}</a></li>
                                        @endforeach
                                    </ul>
                                </li>
                            @endforeach
                        @endisset
                    </ul>

                    <!-- Right Side Of Navbar (Standard guest/auth template buttons) -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        <li class="nav-item">
                            <a class="nav-link text-secondary" href="#"><i class="bi bi-box-arrow-in-right"></i> Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-secondary" href="#"><i class="bi bi-person-plus"></i> Register</a>
                        </li>
                        <li class="nav-item dropdown ms-md-3 border-start ps-md-3">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle fw-semibold text-dark" href="#" role="button" data-bs-toggle="dropdown">
                                <i class="bi bi-person-fill text-primary"></i> Guest Developer
                            </a>

                            <div class="dropdown-menu dropdown-menu-end shadow-sm">
                                <a class="dropdown-item" href="#">
                                    <i class="bi bi-person-gear"></i> User Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="bi bi-lock"></i> Spatie Lockbox
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="#">
                                    <i class="bi bi-box-arrow-left"></i> Logout Session
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Traditional Bootstrap Layout Center Card -->
        <main class="py-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="card auth-card bg-white">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <span><i class="bi bi-tv-fill me-1"></i> Laravel UI Bootstrap Console Workspace</span>
                                <span class="badge bg-secondary">Bootstrap 5 Standard</span>
                            </div>
                            <div class="card-body p-4 p-md-5">
                                @yield('content')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        
        <footer class="footer mt-auto py-4 bg-white border-top">
            <div class="container text-center text-muted small">
                &copy; {{ date('Y') }} ${config.projectName}. Generated via authentic Laravel UI scaffolding.
            </div>
        </footer>
    </div>

    <!-- Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
`;
  } else if (config.bladeTemplateStyle === 'business_portal') {
    files['resources/views/layouts/app.blade.php'] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', '${activePage.title}') - {{ $projectName ?? '${config.projectName}' }}</title>
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    
    <style>
        :root {
            --bs-primary: ${primaryColor};
            --bs-secondary: ${secondaryColor};
            --bs-primary-rgb: ${hexToRgb(primaryColor)};
            --bs-secondary-rgb: ${hexToRgb(secondaryColor)};
            --cms-dark: ${darkColor};
            --cms-light: ${lightColor};
        }
        body {
            font-family: 'Playfair Display', -apple-system, system-ui, serif;
            background-color: var(--cms-light);
            color: var(--cms-dark);
        }
        .navbar-custom {
            border-bottom: 2px solid var(--bs-primary);
            background: #ffffff;
        }
        .mega-dropdown-menu {
            width: 100%;
            padding: 20px;
            border-radius: 0;
            border: none;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>

    <!-- Elegant Sticky Navigation Menu -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom sticky-top">
        <div class="container">
            <a class="navbar-brand fw-bold text-dark" href="{{ route('home') }}">
                <i class="bi bi-building text-primary me-1.5"></i> {{ $projectName ?? '${config.projectName}' }}
            </a>
            <button class="navbar-collapse collapse navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basicNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basicNavbar">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
                    <li class="nav-item">
                        <a class="nav-link active fw-semibold" href="{{ route('home') }}">Home Portal</a>
                    </li>
                    @isset($menuModules)
                        @foreach($menuModules as $mod)
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fw-semibold text-secondary" href="#" role="button" data-bs-toggle="dropdown">
                                    {{ $mod->name }}
                                </a>
                                <ul class="dropdown-menu">
                                    @foreach($mod->submodules as $sub)
                                        <li><a class="dropdown-item" href="{{ $sub->url }}">{{ $sub->name }}</a></li>
                                    @endforeach
                                </ul>
                            </li>
                        @endforeach
                    @endisset
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
`;
  } else {
    // Default 'landing' style
    files['resources/views/layouts/app.blade.php'] = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', '${activePage.title}') - {{ $projectName ?? '${config.projectName}' }}</title>
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet font-display: swap">
    
    <!-- Custom Style variables based on CMS Color Palette -->
    <style>
        :root {
            --bs-primary: ${primaryColor};
            --bs-secondary: ${secondaryColor};
            --bs-primary-rgb: ${hexToRgb(primaryColor)};
            --bs-secondary-rgb: ${hexToRgb(secondaryColor)};
            --cms-dark: ${darkColor};
            --cms-light: ${lightColor};
        }
        body {
            font-family: '${config.colorPalette.fontFamily}', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background-color: var(--cms-light);
            color: var(--cms-dark);
        }
        .btn-primary {
            background-color: var(--bs-primary);
            border-color: var(--bs-primary);
        }
        .btn-primary:hover, .btn-primary:focus {
            background-color: darkslategray; /* slightly darker primary override */
            filter: brightness(0.9);
        }
        .text-primary {
            color: var(--bs-primary) !important;
        }
        .gradient-banner {
            background: linear-gradient(135deg, var(--bs-primary) 0%, var(--bs-secondary) 100%);
            color: white;
        }
        .glass-card {
            background: rgba(255, 255, 255, 0.7);
            backdrop-filter: blur(8px);
            border: 1px solid rgba(255, 255, 255, 0.2);
        }
    </style>
</head>
<body>

    @yield('content')

    <!-- Bootstrap 5 JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
`;
  }

  // 7. resources/views/welcome.blade.php (Home View)
  files['resources/views/welcome.blade.php'] = generateBladeViewString(activePage.blocks, true, config.projectName);

  // 8. Other sub-pages inside resources/views/pages/
  config.pages.filter(p => p.id !== 'home').forEach(p => {
    files[`resources/views/pages/${p.slug}.blade.php`] = generateBladeViewString(p.blocks, false, config.projectName);
  });

  // 9. Laravel Config and Standard Boilerplate files
  files['composer.json'] = `{
    "$schema": "https://getcomposer.org/schema.json",
    "name": "laravel/livewire-starter-kit",
    "type": "project",
    "description": "The official Laravel starter kit for Livewire.",
    "keywords": [
        "laravel",
        "framework"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "laravel/fortify": "^1.30",
        "laravel/framework": "^12.0",
        "laravel/tinker": "^2.10.1",
        "livewire/blaze": "^1.0",
        "livewire/flux": "^2.9.0",
        "livewire/livewire": "^4.2",
        "robsontenorio/mary": "^2.8",
        "spatie/laravel-permission": "^7.2"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "laravel/boost": "2.0",
        "laravel/pail": "^1.2.2",
        "laravel/pint": "^1.24",
        "laravel/sail": "^1.41",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.6",
        "pestphp/pest": "^4.4",
        "pestphp/pest-plugin-laravel": "^4.1"
    },
    "autoload": {
        "psr-4": {
            "App\\\\": "app/",
            "Database\\\\Factories\\\\": "database/factories/",
            "Database\\\\Seeders\\\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\\\": "tests/"
        }
    },
    "scripts": {
        "setup": [
            "composer install",
            "@php -r \\"file_exists('.env') || copy('.env.example', '.env');\\"",
            "@php artisan key:generate",
            "@php artisan migrate --force",
            "npm install",
            "npm run build"
        ],
        "dev": [
            "Composer\\\\Config::disableProcessTimeout",
            "npx concurrently -c \\"#93c5fd,#c4b5fd,#fdba74\\" \\"php artisan serve --no-reload\\" \\"php artisan queue:listen --tries=1\\" \\"npm run dev\\" --names='server,queue,vite'"
        ],
        "lint": [
            "pint --parallel"
        ],
        "lint:check": [
            "pint --parallel --test"
        ],
        "ci:check": [
            "Composer\\\\Config::disableProcessTimeout",
            "@test"
        ],
        "test": [
            "@php artisan config:clear --ansi",
            "@lint:check",
            "@php artisan test"
        ],
        "post-autoload-dump": [
            "Illuminate\\\\Foundation\\\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan boost:update --ansi"
        ],
        "post-root-package-install": [
            "@php -r \\"file_exists('.env') || copy('.env.example', '.env');\\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi",
            "@php -r \\"file_exists('database/database.sqlite') || touch('database/database.sqlite');\\"",
            "@php artisan migrate --graceful --ansi"
        ],
        "pre-package-uninstall": [
            "Illuminate\\\\Foundation\\\\ComposerScripts::prePackageUninstall"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}`;

  files['package.json'] = `{
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "devDependencies": {
    "bootstrap": "^5.3.3",
    "laravel-vite-plugin": "^1.0",
    "vite": "^5.0"
  }
}`;

  files['vite.config.js'] = `import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});`;

  const hostVal = config.dbHost || '127.0.0.1';
  let defaultPort = '3306';
  if (config.dbDriver === 'pgsql') {
    defaultPort = '5432';
  } else if (config.dbDriver === 'sqlite') {
    defaultPort = '';
  }
  const portVal = config.dbPort !== undefined ? config.dbPort : defaultPort;
  const dbNameVal = config.dbDatabase || config.projectName || 'laravel';
  const usernameVal = config.dbUsername !== undefined ? config.dbUsername : 'root';
  const passwordVal = config.dbPassword !== undefined ? config.dbPassword : '';

  files['.env.example'] = `APP_NAME="${config.projectName || 'LaraBoot'}"
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=http://localhost:8000

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=${config.dbDriver || 'sqlite'}
DB_HOST=${hostVal}
DB_PORT=${portVal}
DB_DATABASE=${dbNameVal}
DB_USERNAME=${usernameVal}
DB_PASSWORD=${passwordVal}

SESSION_DRIVER=cookie
SESSION_LIFETIME=120
`;

  files['database/database.sqlite'] = '';

  files['artisan'] = `#!/usr/bin/env php
<?php

// Laravel Command Line Tool
// Generated automatically by LaraBoot CMS Visual Compiler.

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Boot Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\\Contracts\\Console\\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\\Component\\Console\\Input\\ArgvInput,
    new Symfony\\Component\\Console\\Output\\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
`;

  files['bootstrap/app.php'] = `<?php

use Illuminate\\Foundation\\Application;
use Illuminate\\Foundation\\Configuration\\Exceptions;
use Illuminate\\Foundation\\Configuration\\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        // Middleware customized by LaraBoot Studio
    })
    ->withExceptions(function (Exceptions $exceptions) {
        // Exception management
    })->create();
`;

  files['bootstrap/providers.php'] = `<?php

return [
    App\\Providers\\AppServiceProvider::class,
    App\\Providers\\RepositoryServiceProvider::class,
];
`;

  files['app/Providers/AppServiceProvider.php'] = `<?php

namespace App\\Providers;

use Illuminate\\Support\\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        //
    }
}
`;

  files['routes/console.php'] = `<?php

use Illuminate\\Support\\Facades\\Artisan;

Artisan::command('inspire', function () {
    $this->comment(Illuminate\\Foundation\\Inspiring::quote());
})->purpose('Display an inspiring quote');
`;

  files['public/index.php'] = `<?php

use Illuminate\\Http\\Request;

define('LARAVEL_START', microtime(true));

// Determine if the application is in maintenance mode...
if (file_exists($maintenance = __DIR__.'/../storage/framework/maintenance.php')) {
    require $maintenance;
}

// Register the Composer autoloader...
require __DIR__.'/../vendor/autoload.php';

// Bootstrap Laravel and handle the request...
(require_once __DIR__.'/../bootstrap/app.php')
    ->handleRequest(Request::capture());
`;

  files['config/database.php'] = `<?php

return [

    'default' => env('DB_CONNECTION', '${config.dbDriver || 'sqlite'}'),

    'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DB_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => env('DB_CHARSET', 'utf8mb4'),
            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DB_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'laravel'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => env('DB_CHARSET', 'utf8'),
            'prefix' => '',
            'prefix_indexes' => true,
            'search_path' => 'public',
            'sslmode' => 'prefer',
        ],

    ],

    'migrations' => 'migrations',

];
`;

  files['resources/css/app.css'] = `/* Custom Styles compiled by LaraBoot CMS Studio */
@import "bootstrap/dist/css/bootstrap.min.css";
`;

  files['resources/js/app.js'] = `// Main JS compiled by LaraBoot CMS Studio
import 'bootstrap';
`;

  files['README.md'] = `# ${config.projectName} - Laravel CMS Website
Generated with **LaraBoot Visual Builder CMS** on ${new Date().toLocaleDateString()}.

This is a complete, fully engineered Laravel MVC codebase featuring pristine **Bootstrap 5** visual scaffolding, database models, seeders, and routes fully configured.

## Getting Started

1. Extract the contents to your local server directory.
2. Run Composer dependency installs (bypassing restrictive local environment security checks):
   \`\`\`bash
   composer install --no-audit
   \`\`\`
3. Setup your environment config:
   \`\`\`bash
   cp .env.example .env
   php artisan key:generate
   \`\`\`
4. Run Database Migrations and Seed mock blog entries & products:
   \`\`\`bash
   php artisan migrate --seed
   \`\`\`
5. Compile assets and launch development servers:
   \`\`\`bash
   npm install
   npm run dev
   # In another terminal window:
   php artisan serve
   \`\`\`

Open your browser at \`http://localhost:8000\` to experience your Bootstrap design running on Laravel!
`;

  return files;
}

// Convert Hex string color to RGB coordinates for CSS translucent overlays
function hexToRgb(hex: string): string {
  let c = hex.substring(1);
  if (c.length === 3) {
    c = c[0] + c[0] + c[1] + c[1] + c[2] + c[2];
  }
  const num = parseInt(c, 16);
  return `${(num >> 16) & 255}, ${(num >> 8) & 255}, ${num & 255}`;
}

// Subroutine: convert block list directly to highly optimized Laravel Blade code
function generateBladeViewString(blocks: Block[], isHome: boolean, projectName: string = 'Laraboot'): string {
  let content = `@extends('layouts.app')

@section('title', '${isHome ? 'Welcome Portal' : 'Custom Section'}')

@section('content')
`;

  blocks.forEach(block => {
    if (!block.visible) return;

    switch (block.type) {
      case 'navbar': {
        const bgClass = block.themeStyle === 'dark' ? 'bg-dark navbar-dark' : block.themeStyle === 'primary' ? 'bg-primary navbar-dark' : 'bg-light navbar-light';
        content += `
    <!-- Navbar Section: ${block.brand} -->
    <nav class="navbar navbar-expand-lg ${bgClass} ${block.sticky ? 'sticky-top shadow' : ''} py-3">
        <div class="container">
            <a class="navbar-brand fw-bold fs-3" href="#">
                <i class="bi bi-cpu text-primary me-2"></i>{{ $projectName ?? '${block.brand}' }}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navCollapse-${block.id}">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navCollapse-${block.id}">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    ${block.links.map(link => `
                    <li class="nav-item">
                        <a class="nav-link px-3" href="${link.url}">${link.label}</a>
                    </li>`).join('')}
                </ul>
                <a href="${block.ctaLink}" class="btn btn-primary px-4 rounded-pill fw-semibold shadow-sm">${block.ctaText}</a>
            </div>
        </div>
    </nav>
`;
        break;
      }
      case 'hero': {
        let alignClass = 'text-center py-5';
        let rowContent = '';
        const bgClass = block.bgPattern === 'gradient' ? 'gradient-banner' : block.bgPattern === 'glass' ? 'bg-body-tertiary border-bottom py-5 glass-card' : 'bg-body py-5';

        if (block.layout === 'center') {
          rowContent = `
                <div class="col-lg-8 mx-auto">
                    <h1 class="display-4 fw-bold mb-3 tracking-tight">${block.title}</h1>
                    <p class="lead mb-4 opacity-90">${block.subtitle}</p>
                    <div class="d-flex justify-content-center gap-3">
                        <a href="${block.ctaLink}" class="btn btn-primary btn-lg px-4 rounded-pill shadow">${block.ctaText}</a>
                        <a href="${block.secondaryCtaLink}" class="btn btn-outline-dark btn-lg px-4 rounded-pill">${block.secondaryCtaText}</a>
                    </div>
                </div>`;
        } else if (block.layout === 'left-split') {
          rowContent = `
                <div class="col-lg-6 my-auto text-start">
                    <span class="badge bg-primary-subtle text-primary border border-primary-subtle px-3 py-2 rounded-pill mb-3 uppercase tracking-wider">Laravel + Bootstrap</span>
                    <h1 class="display-5 fw-bold mb-3">${block.title}</h1>
                    <p class="lead mb-4 opacity-90">${block.subtitle}</p>
                    <div class="d-flex gap-3">
                        <a href="${block.ctaLink}" class="btn btn-primary btn-lg px-4 rounded-pill shadow-sm">${block.ctaText}</a>
                        <a href="${block.secondaryCtaLink}" class="btn btn-outline-secondary btn-lg px-4 rounded-pill">${block.secondaryCtaText}</a>
                    </div>
                </div>
                <div class="col-lg-6 mt-4 mt-lg-0">
                    <img src="${block.imageUrl}" class="img-fluid rounded-4 shadow-lg border" alt="Hero Mockup" referrerPolicy="no-referrer">
                </div>`;
        } else {
          rowContent = `
                <div class="col-lg-6 mb-4 my-auto">
                    <img src="${block.imageUrl}" class="img-fluid rounded-4 shadow-lg border" alt="Hero Mockup" referrerPolicy="no-referrer">
                </div>
                <div class="col-lg-6 my-auto text-start ps-lg-5">
                    <h1 class="display-5 fw-bold mb-3">${block.title}</h1>
                    <p class="lead mb-4 opacity-90">${block.subtitle}</p>
                    <div class="d-flex gap-3">
                        <a href="${block.ctaLink}" class="btn btn-primary btn-lg px-4 rounded-pill shadow-sm">${block.ctaText}</a>
                        <a href="${block.secondaryCtaLink}" class="btn btn-outline-secondary btn-lg px-4 rounded-pill">${block.secondaryCtaText}</a>
                    </div>
                </div>`;
        }

        content += `
    <!-- Hero Block -->
    <header class="${bgClass} py-5 border-bottom">
        <div class="container py-4">
            <div class="row align-items-center">
                ${rowContent}
            </div>
        </div>
    </header>
`;
        break;
      }
      case 'features': {
        const colClass = block.columns === 4 ? 'col-lg-3' : block.columns === 2 ? 'col-lg-6' : 'col-lg-4';
        content += `
    <!-- Features Block: ${block.title} -->
    <section id="features" class="py-5 bg-body-secondary">
        <div class="container py-4 text-center">
            <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
            <p class="text-secondary col-md-8 mx-auto mb-5 lead">${block.subtitle}</p>
            <div class="row g-4 text-start">
                ${block.items.map(item => `
                <div class="${colClass} col-md-6">
                    <div class="card h-100 p-4 border shadow-sm rounded-4 bg-body">
                        <div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 text-primary fs-3 rounded-3 p-3 mb-3" style="width: 56px; height: 56px;">
                            <i class="bi ${getBootstrapIconClass(item.icon)}"></i>
                        </div>
                        <h4 class="fw-bold mb-2 text-dark">${item.title}</h4>
                        <p class="text-secondary small mb-0">${item.description}</p>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'stats': {
        content += `
    <!-- Stats Banner: ${block.title} -->
    <section class="py-5 gradient-banner text-center text-white">
        <div class="container py-3">
            <h3 class="fw-bold mb-3">${block.title}</h3>
            <p class="lead opacity-90 col-md-8 mx-auto mb-5">${block.subtitle}</p>
            <div class="row g-4 justify-content-center">
                ${block.items.map(item => `
                <div class="col-6 col-md-3">
                    <h2 class="display-4 fw-extrabold mb-1">${item.number}</h2>
                    <p class="text-uppercase tracking-wider small opacity-75 mb-0">${item.label}</p>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'blog': {
        content += `
    <!-- Blog Section -->
    <section id="blog" class="py-5 bg-body">
        <div class="container py-4">
            <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-5">
                <div>
                    <h2 class="fw-bold text-dark display-6 mb-1">${block.title}</h2>
                    <p class="text-secondary lead mb-0">${block.subtitle}</p>
                </div>
                <a href="#" class="btn btn-outline-primary rounded-pill mt-3 mt-md-0 px-4">View All Publications</a>
            </div>

            @if(isset($blogs) && count($blogs) > 0)
                <div class="row g-4">
                    @foreach($blogs as $post)
                        <div class="col-lg-6">
                            <div class="card h-100 border rounded-4 overflow-hidden shadow-sm bg-body">
                                <div class="row g-0 h-100">
                                    <div class="col-md-5">
                                        <img src="{{ $post->image_url ?? 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=400&q=80' }}" class="img-fluid h-100 object-fit-cover w-full" style="min-height: 200px;" alt="{{ $post->title }}">
                                    </div>
                                    <div class="col-md-7 d-flex flex-column p-4">
                                        <span class="badge bg-secondary-subtle text-secondary align-self-start mb-2">{{ $post->category ?? 'News' }}</span>
                                        <h5 class="fw-bold text-dark"><a href="#" class="text-decoration-none text-dark">{{ $post->title }}</a></h5>
                                        <p class="text-secondary small flex-grow-1">{{ Str::limit($post->excerpt, 100) }}</p>
                                        <div class="d-flex align-items-center mt-3 pt-3 border-top justify-content-between">
                                            <span class="text-secondary small fw-semibold">{{ $post->author ?? 'Editorial Staff' }}</span>
                                            <span class="text-muted small">{{ $post->created_at ? $post->created_at->format('M d, Y') : 'June 2026' }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            @else
                <!-- Static Fallback Content when not run in production server -->
                <div class="row g-4">
                    <div class="col-lg-6">
                        <div class="card h-100 border rounded-4 overflow-hidden shadow-sm bg-body">
                            <div class="row g-0">
                                <div class="col-md-5">
                                    <img src="https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=400&q=80" class="img-fluid h-100 object-fit-cover" alt="CMS Dev">
                                </div>
                                <div class="col-md-7 p-4 d-flex flex-column justify-content-between">
                                    <div>
                                        <span class="badge bg-secondary-subtle text-secondary mb-2">DevOps</span>
                                        <h5 class="fw-bold text-dark">Deploying Laravel 11 on Modern VPS Hosting</h5>
                                        <p class="text-secondary small">Learn the step-by-step procedure to config PHP 8.3, Nginx, and systemd with custom seeders.</p>
                                    </div>
                                    <div class="text-muted small">Sarah Taylor | June 2026</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </section>
`;
        break;
      }
      case 'pricing': {
        content += `
    <!-- Pricing Section: ${block.title} -->
    <section id="pricing" class="py-5 bg-body-secondary">
        <div class="container py-4 text-center">
            <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
            <p class="text-secondary lead col-md-8 mx-auto mb-5">${block.subtitle}</p>
            <div class="row g-4 justify-content-center text-start">
                ${block.tiers.map(tier => `
                <div class="col-lg-4 col-md-6">
                    <div class="card h-100 p-4 border ${tier.featured ? 'border-primary border-3 shadow-lg scale-up' : 'shadow-sm'} rounded-4 bg-body d-flex flex-column">
                        ${tier.featured ? '<span class="badge bg-primary text-white rounded-pill px-3 py-2 align-self-start mb-3 uppercase tracking-wider">Most Popular</span>' : ''}
                        <h4 class="fw-bold text-dark mb-1">${tier.name}</h4>
                        <div class="d-flex align-items-baseline mb-3">
                            <span class="display-5 fw-bold text-dark">${tier.price}</span>
                            <span class="text-secondary ms-2">${tier.billing}</span>
                        </div>
                        <ul class="list-unstyled flex-grow-1 border-top pt-3 mb-4">
                            ${tier.features.map(f => `
                            <li class="mb-2 d-flex align-items-center">
                                <i class="bi bi-patch-check-fill text-success me-2"></i>
                                <span class="text-secondary">${f}</span>
                            </li>`).join('')}
                        </ul>
                        <a href="#" class="btn ${tier.featured ? 'btn-primary' : 'btn-outline-dark'} btn-lg w-full rounded-pill shadow-sm py-2 fw-semibold">${tier.ctaText}</a>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'testimonials': {
        content += `
    <!-- Testimonials Section -->
    <section class="py-5 bg-body">
        <div class="container py-4 text-center">
            <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
            <p class="text-secondary col-md-8 mx-auto mb-5 lead">${block.subtitle}</p>
            <div class="row g-4 text-start">
                ${block.items.map(item => `
                <div class="col-md-6 col-lg-4">
                    <div class="card h-100 p-4 border rounded-4 shadow-sm bg-body d-flex flex-column justify-content-between">
                        <div>
                            <div class="text-warning mb-3">
                                ${Array.from({ length: item.stars }).map(() => '<i class="bi bi-star-fill me-1"></i>').join('')}
                            </div>
                            <p class="text-secondary italic mb-4">"${item.text}"</p>
                        </div>
                        <div class="d-flex align-items-center border-top pt-3">
                            <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-flex align-items-center justify-content-center fw-bold me-3" style="width: 44px; height: 44px;">
                                ${item.author[0]}
                            </div>
                            <div>
                                <h6 class="fw-bold text-dark mb-0">${item.author}</h6>
                                <small class="text-muted">${item.role}</small>
                            </div>
                        </div>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'gallery': {
        const colClass = block.columns === 4 ? 'col-lg-3' : 'col-lg-4';
        content += `
    <!-- Gallery Block: ${block.title} -->
    <section class="py-5 bg-body-secondary">
        <div class="container py-4">
            <div class="text-center mb-5">
                <h2 class="fw-bold text-dark display-6 mb-2">${block.title}</h2>
                <p class="text-secondary lead col-md-8 mx-auto">${block.subtitle}</p>
            </div>
            <div class="row g-4">
                ${block.items.map(img => `
                <div class="${colClass} col-md-6">
                    <div class="card h-100 overflow-hidden border shadow-sm rounded-4 bg-body">
                        <img src="${img.imageUrl}" class="img-fluid" style="height: 220px; object-fit: cover;" alt="${img.title}" referrerPolicy="no-referrer">
                        <div class="p-3">
                            <h5 class="fw-bold text-dark mb-1">${img.title}</h5>
                            <p class="text-secondary small mb-0">${img.description}</p>
                        </div>
                    </div>
                </div>`).join('')}
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'contact': {
        content += `
    <!-- Contact/Form Block -->
    <section id="contact" class="py-5 bg-body">
        <div class="container py-4">
            <div class="row g-5 align-items-stretch">
                <div class="col-lg-5 d-flex flex-column justify-content-between">
                    <div>
                        <span class="badge bg-primary-subtle text-primary border border-primary-subtle px-3 py-2 rounded-pill mb-3">Support & Launch</span>
                        <h2 class="fw-bold text-dark display-6 mb-3">${block.title}</h2>
                        <p class="text-secondary mb-4 lead">${block.subtitle}</p>
                    </div>
                    <div class="mb-4">
                        <div class="d-flex align-items-center mb-3">
                            <span class="bg-primary bg-opacity-10 text-primary p-2 rounded-3 me-3 fs-3"><i class="bi bi-envelope"></i></span>
                            <div>
                                <h6 class="fw-bold mb-0">Email Address</h6>
                                <span class="text-secondary small">${block.email}</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center mb-3">
                            <span class="bg-primary bg-opacity-10 text-primary p-2 rounded-3 me-3 fs-3"><i class="bi bi-telephone"></i></span>
                            <div>
                                <h6 class="fw-bold mb-0">Telephone Support</h6>
                                <span class="text-secondary small">${block.phone}</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="bg-primary bg-opacity-10 text-primary p-2 rounded-3 me-3 fs-3"><i class="bi bi-geo-alt"></i></span>
                            <div>
                                <h6 class="fw-bold mb-0">Silicon HQ Location</h6>
                                <span class="text-secondary small">${block.address}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7">
                    <form class="card p-4 p-md-5 border shadow-sm rounded-4 bg-body" onsubmit="event.preventDefault(); alert('Standard Laravel Form Action simulation success! Thank you.');">
                        <div class="row g-3">
                            <div class="col-md-6">
                                <label class="form-label text-secondary small fw-semibold">Your Full Name</label>
                                <input type="text" class="form-control rounded-pill py-2 px-3" required placeholder="Alex Mercer">
                            </div>
                            <div class="col-md-6">
                                <label class="form-label text-secondary small fw-semibold">Email Account</label>
                                <input type="email" class="form-control rounded-pill py-2 px-3" required placeholder="alex@mercer.com">
                            </div>
                            <div class="col-12">
                                <label class="form-label text-secondary small fw-semibold">Inquiry Subject</label>
                                <input type="text" class="form-control rounded-pill py-2 px-3" required placeholder="Laravel Deployment Assistance">
                            </div>
                            <div class="col-12">
                                <label class="form-label text-secondary small fw-semibold">Message Body</label>
                                <textarea class="form-control rounded-3" rows="4" required placeholder="Please describe your operational needs here..."></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary rounded-pill w-100 py-3 fw-semibold shadow-sm mt-3">${block.buttonText}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
`;
        break;
      }
      case 'footer': {
        content += `
    <!-- Footer section -->
    <footer class="py-5 bg-dark text-white border-top">
        <div class="container py-3">
            <div class="row g-4 align-items-center justify-content-between">
                <div class="col-md-5">
                    <h5 class="fw-bold text-white mb-3"><i class="bi bi-cpu text-primary me-2"></i>{{ $projectName ?? '${projectName}' }}</h5>
                    <p class="text-secondary small mb-0">${block.text}</p>
                </div>
                <div class="col-md-4 text-md-end text-start">
                    <h6 class="fw-bold text-white mb-2">Connect Digitally</h6>
                    <div class="d-flex justify-content-md-end gap-3 mb-3">
                        ${block.socials.map(soc => `
                        <a href="${soc.url}" class="text-white text-decoration-none bg-secondary bg-opacity-25 rounded-circle d-inline-flex align-items-center justify-content-center shadow-sm" style="width: 40px; height: 40px;">
                            <i class="bi bi-${soc.platform.toLowerCase() === 'twitter' ? 'twitter-x' : soc.platform.toLowerCase()}"></i>
                        </a>`).join('')}
                    </div>
                </div>
            </div>
            <div class="border-top border-secondary mt-4 pt-4 text-center">
                <p class="text-secondary small mb-0">${block.copyright}</p>
            </div>
        </div>
    </footer>
`;
        break;
      }
    }
  });

  content += `
@endsection
`;
  return content;
}
